[project]
name = "some-asm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "libsass>=0.23.0",
    "pyqt6>=6.9.1",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

